# Generated by Django 5.2.7 on 2025-11-24 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='traders/')),
                ('duration_days', models.IntegerField()),
                ('daily_roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trading_fee_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='copy_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='current_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='roi_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='CopyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_copying', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opened_date', models.DateTimeField(auto_now_add=True)),
                ('trade_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_trades', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='account.trader')),
            ],
        ),
    ]
