# Generated by Django 5.2.7 on 2025-11-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_trader_user_copy_expenses_user_current_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='trader',
            name='active_investors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='duration_weeks',
            field=models.IntegerField(default=4, help_text='Duration in weeks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trader',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trader',
            name='risk_level',
            field=models.DecimalField(decimal_places=1, default=2.2, help_text='e.g. 2.2', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trader',
            name='total_investors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=95, help_text='e.g. 95 (%)', max_digits=5),
            preserve_default=False,
        ),
    ]
