# Generated by Django 5.2.7 on 2025-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_trader_duration_days_trader_active_investors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ruby', 'Ruby Plan'), ('diamond', 'Diamond Plan'), ('sapphire', 'Sapphire Plan')], max_length=20, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('referral_commission', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trade_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_months', models.PositiveIntegerField()),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
