# Generated by Django 5.2.7 on 2025-11-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='account.investmentplan'),
        ),
    ]
