# Generated by Django 5.2.7 on 2025-11-25 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_portfolio_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('live_trade', 'Live Trade'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('win', 'Win'), ('completed', 'Completed'), ('pending', 'Pending'), ('approved', 'Approved'), ('lost', 'Lost')], max_length=20)),
                ('image', models.ImageField(default='images/2.png', upload_to='transactions')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
