# Generated by Django 5.2.7 on 2025-11-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_paymentmethod_alter_copytrade_trade_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='wallet_address',
            field=models.CharField(default='fdsdfsfd', max_length=250),
            preserve_default=False,
        ),
    ]
