# Generated by Django 5.2.7 on 2025-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_paymentmethod_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
