# Generated by Django 5.2.7 on 2025-11-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('profit', 'Profit')], default='balance', max_length=10),
            preserve_default=False,
        ),
    ]
