# Generated by Django 5.2.7 on 2025-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_marketcategory_marketasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_charge', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='available_for_withdraw',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
