# Generated by Django 5.2.7 on 2025-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_config_withdrawal_available_for_withdraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
