# Generated by Django 5.2.7 on 2025-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_kycverification_rejected_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
