# Generated by Django 5.2.7 on 2025-11-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='psw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
