# Generated by Django 5.2.7 on 2025-11-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_user_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='message_format',
            field=models.CharField(blank=True, choices=[('popup', 'popup'), ('message', 'message')], max_length=100, null=True),
        ),
    ]
