# Generated by Django 5.2.7 on 2025-11-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_user_custom_message_user_message_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='site_mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='site_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
