# Generated by Django 5.2.7 on 2025-11-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_config_email_config_site_mobile_config_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
