# Generated by Django 5.2.7 on 2025-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_investmentplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
