# Generated by Django 5.2.7 on 2025-11-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_investmentplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='duration_multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='maximum_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='plan_type',
            field=models.CharField(default='short', max_length=10),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='recurring_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='term',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
