# Generated by Django 5.2.7 on 2025-11-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_investmentplan_duration_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplan',
            name='duration_months',
        ),
    ]
