# Generated by Django 5.2.7 on 2025-11-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_investmentplan_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
