# Generated by Django 5.2.7 on 2025-11-27 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_last_login_ip_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=20)),
                ('striker', models.CharField(max_length=20)),
                ('interval', models.CharField(max_length=10)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
