# Generated by Django 5.2.7 on 2025-11-27 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_livetrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetrade',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
