# Generated by Django 5.2.7 on 2025-11-27 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_livetrade_opened_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-Active')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('live_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_records', to='account.livetrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
