# Generated by Django 5.2.7 on 2025-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_transaction_content_type_transaction_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('live_trade', 'Live Trade'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('trade', 'Trade')], max_length=20),
        ),
    ]
