# Generated by Django 5.2.7 on 2025-11-28 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.trader'),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
