# Generated by Django 5.2.7 on 2025-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_livetrade_trader_alter_livetrade_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='outcome',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('lost', 'Lost'), ('draw', 'Draw')], max_length=20, null=True),
        ),
    ]
