# Generated by Django 5.2.7 on 2025-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_livetrade_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
