# Generated by Django 5.2.7 on 2025-12-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_livetrade_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='withdrawal_percentage',
            field=models.FloatField(default=5.0),
        ),
    ]
