# Generated by Django 5.2.7 on 2025-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_config_withdrawal_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawal_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
