# Generated by Django 5.2.7 on 2025-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_user_withdrawal_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(default='deposit', max_length=20),
        ),
    ]
