# Generated by Django 5.2.7 on 2025-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_payment_payment_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bot_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
