# Generated by Django 5.2.7 on 2025-12-15 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_config_bot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.portfolio'),
        ),
    ]
