# Generated by Django 5.2.7 on 2025-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_payment_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
    ]
