# Generated by Django 5.2.7 on 2025-12-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_livetrade_admin_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetrade',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
