# Generated by Django 5.2.7 on 2025-12-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_livetrade_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
